### Clean up of downloaded data from GeyserTimes.com and geyserstudy.org

In [21]:
import pandas as pd
import datetime as dt
import re

In [22]:
df = pd.read_csv('old_faithful.csv', index_col='eruptionID')
df.head()

C:\Users\Geopetal Energy\anaconda\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (21) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,geyser,eruption_time_epoch,has_seconds,exact,ns,ie,E,A,wc,ini,...,duration,entrant,observer,eruption_comment,time_updated,time_entered,associated_primaryID,other_comments,Old_Faithful_Preplay_Time_VEC,Old_Faithful_Height_VEC
eruptionID,,,,,,,,,,,,,,,,,,,,,
23132,Old Faithful,10506540,0,1,0,0,0,0,0,0,...,4min,BoekelUpload,OFVCL-EV,NaN,1335129843,1335129843,23132,NaN,NaN,NaN
23133,Old Faithful,10510800,0,1,0,0,0,0,0,0,...,1.5min,BoekelUpload,OFVCL-EV,NaN,1335129876,1335129876,23133,NaN,NaN,NaN
23134,Old Faithful,10513800,0,1,0,0,0,0,0,0,...,4.25m,BoekelUpload,OFVCL-EV,NaN,1335129909,1335129909,23134,NaN,NaN,NaN
23135,Old Faithful,10517820,0,1,0,0,0,0,0,0,...,4m,BoekelUpload,OFVCL-EV,NaN,1335129944,1335129944,23135,NaN,NaN,NaN
23136,Old Faithful,10522680,0,1,0,0,0,0,0,0,...,1.75min,BoekelUpload,OFVCL-EV,NaN,1335130069,1335130069,23136,NaN,NaN,NaN

In [3]:
df.columns

Index(['geyser', 'eruption_time_epoch', 'has_seconds', 'exact', 'ns', 'ie',
       'E', 'A', 'wc', 'ini', 'maj', 'min', 'q', 'duration', 'entrant',
       'observer', 'eruption_comment', 'time_updated', 'time_entered',
       'associated_primaryID', 'other_comments',
       'Old_Faithful_Preplay_Time_VEC', 'Old_Faithful_Height_VEC'],
      dtype='object')

In [23]:
df.drop(['has_seconds', 'exact', 'ns', 'ie', 'E', 'A', 'wc', 'entrant','ini', 'maj', 'min', 'q','eruption_comment', 'time_updated', 'time_entered',
       'associated_primaryID', 'other_comments','Old_Faithful_Preplay_Time_VEC','Old_Faithful_Height_VEC'], axis=1, inplace=True)

In [24]:
df['date'] = pd.to_datetime(df['eruption_time_epoch'], unit='s')

In [25]:
df.head()

,geyser,eruption_time_epoch,duration,observer,date
eruptionID,,,,,
23132,Old Faithful,10506540,4min,OFVCL-EV,1970-05-02 14:29:00
23133,Old Faithful,10510800,1.5min,OFVCL-EV,1970-05-02 15:40:00
23134,Old Faithful,10513800,4.25m,OFVCL-EV,1970-05-02 16:30:00
23135,Old Faithful,10517820,4m,OFVCL-EV,1970-05-02 17:37:00
23136,Old Faithful,10522680,1.75min,OFVCL-EV,1970-05-02 18:58:00

In [26]:
df['year'] = df['date'].dt.year
df.head()

,geyser,eruption_time_epoch,duration,observer,date,year
eruptionID,,,,,,
23132,Old Faithful,10506540,4min,OFVCL-EV,1970-05-02 14:29:00,1970
23133,Old Faithful,10510800,1.5min,OFVCL-EV,1970-05-02 15:40:00,1970
23134,Old Faithful,10513800,4.25m,OFVCL-EV,1970-05-02 16:30:00,1970
23135,Old Faithful,10517820,4m,OFVCL-EV,1970-05-02 17:37:00,1970
23136,Old Faithful,10522680,1.75min,OFVCL-EV,1970-05-02 18:58:00,1970

In [27]:
df["waiting_time_mins"] = df["eruption_time_epoch"].diff(-1)/60
df.tail()

,geyser,eruption_time_epoch,duration,observer,date,year,waiting_time_mins
eruptionID,,,,,,,
1112210,Old Faithful,1562807400,NaN,NaN,2019-07-11 01:10:00,2019,-95.0
1112217,Old Faithful,1562813100,NaN,NaN,2019-07-11 02:45:00,2019,-117.0
1112226,Old Faithful,1562820120,NaN,NaN,2019-07-11 04:42:00,2019,-82.0
1112231,Old Faithful,1562825040,NaN,NaN,2019-07-11 06:04:00,2019,-98.0
1112232,Old Faithful,1562830920,NaN,NaN,2019-07-11 07:42:00,2019,NaN

In [28]:
df["waiting_time_hrs"] = df["eruption_time_epoch"].diff(-1)/3600
df.head()

,geyser,eruption_time_epoch,duration,observer,date,year,waiting_time_mins,waiting_time_hrs
eruptionID,,,,,,,,
23132,Old Faithful,10506540,4min,OFVCL-EV,1970-05-02 14:29:00,1970,-71.0,-1.183333
23133,Old Faithful,10510800,1.5min,OFVCL-EV,1970-05-02 15:40:00,1970,-50.0,-0.833333
23134,Old Faithful,10513800,4.25m,OFVCL-EV,1970-05-02 16:30:00,1970,-67.0,-1.116667
23135,Old Faithful,10517820,4m,OFVCL-EV,1970-05-02 17:37:00,1970,-81.0,-1.350000
23136,Old Faithful,10522680,1.75min,OFVCL-EV,1970-05-02 18:58:00,1970,-43.0,-0.716667

In [29]:
df['dur'] = df['duration'].str.findall('\d+')

In [30]:
df.tail()

,geyser,eruption_time_epoch,duration,observer,date,year,waiting_time_mins,waiting_time_hrs,dur
eruptionID,,,,,,,,,
1112210,Old Faithful,1562807400,NaN,NaN,2019-07-11 01:10:00,2019,-95.0,-1.583333,NaN
1112217,Old Faithful,1562813100,NaN,NaN,2019-07-11 02:45:00,2019,-117.0,-1.950000,NaN
1112226,Old Faithful,1562820120,NaN,NaN,2019-07-11 04:42:00,2019,-82.0,-1.366667,NaN
1112231,Old Faithful,1562825040,NaN,NaN,2019-07-11 06:04:00,2019,-98.0,-1.633333,NaN
1112232,Old Faithful,1562830920,NaN,NaN,2019-07-11 07:42:00,2019,NaN,NaN,NaN

In [31]:
df.to_csv('geyser_times_data.csv', encoding='utf-8', index=True)

In [32]:
df['year'].unique()

array([1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1992, 1993, 1994,
       1995, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
       2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019],
      dtype=int64)

In [68]:
master_df = pd.read_csv('all_years.csv', index_col='eruptionID')

C:\Users\Geopetal Energy\anaconda\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [69]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 168352 entries, 23132 to 1112232
Data columns (total 9 columns):
geyser                 168352 non-null object
eruption_time_epoch    168352 non-null int64
duration               39293 non-null object
observer               108140 non-null object
date                   168352 non-null object
year                   168352 non-null int64
waiting_min            168346 non-null object
waiting_hr             168346 non-null object
dur                    39255 non-null object
dtypes: int64(2), object(7)
memory usage: 12.8+ MB

In [70]:
master_df

,geyser,eruption_time_epoch,duration,observer,date,year,waiting_min,waiting_hr,dur
eruptionID,,,,,,,,,
23132,Old Faithful,10506540,4min,OFVCL-EV,5/2/1970 14:29,1970,71,1.18,4.00
23133,Old Faithful,10510800,1.5min,OFVCL-EV,5/2/1970 15:40,1970,50,0.83,1.50
23134,Old Faithful,10513800,4.25m,OFVCL-EV,5/2/1970 16:30,1970,67,1.12,4.25
23135,Old Faithful,10517820,4m,OFVCL-EV,5/2/1970 17:37,1970,81,1.35,4.00
23136,Old Faithful,10522680,1.75min,OFVCL-EV,5/2/1970 18:58,1970,43,0.72,1.75
23137,Old Faithful,10525260,4.5min,OFVCL-EV,5/2/1970 19:41,1970,70,1.17,4.50
23138,Old Faithful,10529460,4min,OFVCL-EV,5/2/1970 20:51,1970,66,1.10,4.00
23139,Old Faithful,10533420,4min,OFVCL-EV,5/2/1970 21:57,1970,69,1.15,4.00
23140,Old Faithful,10537560,NaN,OFVCL-EV,5/2/1970 23:06,1970,932,15.53,NaN
23145,Old Faithful,10593480,4min,OFVCL-EV,5/3/1970 14:38,1970,70,1.17,4.00
23146,Old Faithful,10597680,2min,OFVCL-EV,5/3/1970 15:48,1970,44,0.73,2.00
23147,Old Faithful,10600320,4.25min,OFVCL-EV,5/3/1970 16:32,1970,88,1.47,4.25
23148,Old Faithful,10605600,1.75min,OFVCL-EV,5/3/1970 18:00,1970,46,0.77,1.75
23150,Old Faithful,10608360,4min,OFVCL-EV,5/3/1970 18:46,1970,66,1.10,4.00
23152,Old Faithful,10612320,2.25min,OFVCL-EV,5/3/1970 19:52,1970,54,0.90,2.25
23153,Old Faithful,10615560,4min,OFVCL-EV,5/3/1970 20:46,1970,75,1.25,4.00
23154,Old Faithful,10620060,2min,OFVCL-EV,5/3/1970 22:01,1970,49,0.82,2.00
23151,Old Faithful,10623000,4min,OFVCL-EV,5/3/1970 22:50,1970,934,15.57,4.00
23155,Old Faithful,10679040,4.25min,OFVCL-EV,5/4/1970 14:24,1970,75,1.25,4.25
23158,Old Faithful,10683540,2.5min,OFVCL-EV,5/4/1970 15:39,1970,55,0.92,2.50
23159,Old Faithful,10686840,4.5min,OFVCL-EV,5/4/1970 16:34,1970,69,1.15,4.50
23167,Old Faithful,10690980,3+min,OFVCL-EV,5/4/1970 17:43,1970,88,1.47,3.00
23168,Old Faithful,10696260,2min,OFVCL-EV,5/4/1970 19:11,1970,38,0.63,2.00
23169,Old Faithful,10698540,4min,OFVCL-EV,5/4/1970 19:49,1970,83,1.38,4.00
23170,Old Faithful,10703520,2min,OFVCL-EV,5/4/1970 21:12,1970,58,0.97,2.00
23171,Old Faithful,10707000,4min,OFVCL-EV,5/4/1970 22:10,1970,937,15.62,4.00
23174,Old Faithful,10763220,NaN,OFVCL-EV,5/5/1970 13:47,1970,66,1.10,NaN
23175,Old Faithful,10767180,2.5min,OFVCL-EV,5/5/1970 14:53,1970,72,1.20,2.50
23176,Old Faithful,10771500,2.75min,OFVCL-EV,5/5/1970 16:05,1970,63,1.05,2.75
23177,Old Faithful,10775280,4.5,OFVCL-EV,5/5/1970 17:08,1970,142,2.37,4.50
...,...,...,...,...,...,...,...,...,...
1111993,Old Faithful,1562675880,NaN,NaN,7/9/2019 12:38,2019,98,1.63,NaN
1111998,Old Faithful,1562681760,NaN,NaN,7/9/2019 14:16,2019,89,1.48,NaN
1112025,Old Faithful,1562687100,NaN,NaN,7/9/2019 15:45,2019,0,0,NaN
1112026,Old Faithful,1562687100,NaN,NaN,7/9/2019 15:45,2019,101,1.68,NaN
1112039,Old Faithful,1562693160,3min 16sec,NaN,7/9/2019 17:26,2019,94,1.57,3.16
1112042,Old Faithful,1562698800,NaN,NaN,7/9/2019 19:00,2019,86,1.43,NaN
1112045,Old Faithful,1562703960,NaN,NaN,7/9/2019 20:26,2019,105,1.75,NaN
1112047,Old Faithful,1562710260,NaN,NaN,7/9/2019 22:11,2019,102,1.7,NaN
1112058,Old Faithful,1562716380,NaN,lgangi,7/9/2019 23:53,2019,89,1.48,NaN
1112070,Old Faithful,1562721720,NaN,lgangi,7/10/2019 1:22,2019,103,1.72,NaN
1112079,Old Faithful,1562727900,NaN,NaN,7/10/2019 3:05,2019,0,0,NaN
1112080,Old Faithful,1562727900,NaN,lgangi,7/10/2019 3:05,2019,562,9.37,NaN
1112128,Old Faithful,1562761620,NaN,NaN,7/10/2019 12:27,2019,94,1.57,NaN
1112136,Old Faithful,1562767260,NaN,NaN,7/10/2019 14:01,2019,0,0,NaN
1112137,Old Faithful,1562767260,NaN,lgangi,7/10/2019 14:01,2019,88,1.47,NaN
1112144,Old Faithful,1562772540,NaN,NaN,7/10/2019 15:29,2019,98,1.63,NaN
1112157,Old Faithful,1562778420,NaN,NaN,7/10/2019 17:07,2019,0,0,NaN
1112158,Old Faithful,1562778420,NaN,NaN,7/10/2019 17:07,2019,99,1.65,NaN
1112167,Old Faithful,1562784360,NaN,NaN,7/10/2019 18:46,2019,95,1.58,NaN
1112176,Old Faithful,1562790060,NaN,NaN,7/10/2019 20:21,2019,0,0,NaN
1112180,Old Faithful,1562790060,~4m00s,NaN,7/10/2019 20:21,2019,97,1.62,4
1112186,Old Faithful,1562795880,NaN,NaN,7/10/2019 21:58,2019,0,0,NaN
1112187,Old Faithful,1562795880,~3m58s,NaN,7/10/2019 21:58,2019,94,1.57,3.58
1112191,Old Faithful,1562801520,NaN,NaN,7/10/2019 23:32,2019,92,1.53,NaN
1112209,Old Faithful,1562807040,NaN,NaN,7/11/2019 1:04,2019,6,0.1,NaN
1112210,Old Faithful,1562807400,NaN,NaN,7/11/2019 1:10,2019,95,1.58,NaN
1112217,Old Faithful,1562813100,NaN,NaN,7/11/2019 2:45,2019,117,1.95,NaN
1112226,Old Faithful,1562820120,NaN,NaN,7/11/2019 4:42,2019,82,1.37,NaN
1112231,Old Faithful,1562825040,NaN,NaN,7/11/2019 6:04,2019,98,1.63,NaN
1112232,Old Faithful,1562830920,NaN,NaN,7/11/2019 7:42,2019,0,0,NaN

In [ ]:
df_waiting['waiting_min']=pd.to_numeric(df_waiting['waiting_min'],errors='coerce')
df_waiting.info()

In [ ]:
df_waiting = df_waiting.loc[~df_waiting['waiting_min'].isna()]
df_waiting.info()

In [ ]:
df_wait_filt = df_waiting[(df_waiting['waiting_min'] < 200)]

In [ ]:
filt_df = df_wait_filt[(df_wait_filt['waiting_min']> 2)]

In [ ]:
filt_df.count()

In [ ]:
filt_df.to_csv('waiting_filtered.csv', encoding='utf-8', index=True)

In [ ]:
duration_df = filt_df.dropna()

In [ ]:
duration_df.count()

In [ ]:
duration_df.to_csv('duration.csv', encoding='utf-8', index=True)